### ISSUE TITLE
`impl FromStream for IgnoredAny`

### ISSUE THREAD

**Issue by DrewMcArthur** [haydnv/destream#2]
I've implemented my deserialization, and was running into an issue where I wanted to skip over one of the keys in the map.  to do this via serde, i have this - otherwise, i get an error where the deserializer gets some unexpected characters.

```rust
while let Some(key) = map.next_key::<String>()? {
    match key.as_str() {
        ...
        _ => _ = map.next_value::<IgnoredAny>()?,
    }
}
```

In order to do the same for my `FromStream` implementation, we'll need to implement `FromStream` for `IgnoredAny`.  This is the compiler error I get now: 

```
the trait bound `IgnoredAny: FromStream` is not satisfied
the following other types implement trait `FromStream`:
```

I'll open a pull request for this shortly, since I'll just be following the implementation in `serde` [here](https://github.com/serde-rs/serde/blob/master/serde/src/de/ignored_any.rs).

thanks for this crate, it's incredibly helpful!

**Comment by DrewMcArthur** [comment]
after testing my changes in #3 , it seem like we also need to beef up [`ignore_value` in `destream_json`](https://github.com/haydnv/destream_json/blob/main/src/de.rs#L448) to better match the functionality in [`serde_json`](https://github.com/serde-rs/json/blob/fedf8341eedd6fc0ad5c5336d1747463c7d85ece/src/de.rs#L1094)

**Comment by haydnv** [comment]
Thank you for the contribution! Feel free to improve support for ignored values in destream_json

**Comment by DrewMcArthur** [comment]
will do! happy to see this got merged so quickly.  I'll open an issue in that repo to track those changes.  so far they seem quite a bit more in depth than these changes, so i'd love to get your input there once I start the discussion!  thanks again for providing this crate 😄
